name: Publish to Maven Central

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to Maven Central
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
          cache: 'gradle'
      - name: Make ./gradlew executable
        run: chmod +x ./gradlew
      - name: Build and test
        run: ./gradlew build
      - name: Publish to Maven Central
        run: ./gradlew publishMavenPublicationToOssrhRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
